FROM alpine:3.10.1

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories \
    && apk --update add yarn bash \
    && yarn add global serve \
    && rm -rf /var/cache/apk/*

CMD serve ./dist/
