FROM alpine:3.10.1

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories \
    && apk --update add yarn bash \
    && yarn add global umi \
    && rm -rf /var/cache/apk/*

CMD cd /build/ && yarn

# docker run --rm -v $(pwd):/build/ THIS_IMAGE_NAME
